### ISSUE TITLE
PyVDRive Release - March 2019

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#140]
This is a master issue for PyVDRive's release in March 2019.

An equivalent [issue](https://code-int.ornl.gov/ndav/software_plan_tracking/issues/346) is generated in NDAV's software planning tracking.

**Description:**

`PyVDrive March 2019 release` aims to let user to reduce VULCAN data by PyVDRive completely.

Goals:

- Support VDRIVE's Data Reduction Commands
  - [ ] VBIN #347 
  - [ ] CHOP #348 
  - [ ] VPEAK #349
  - [ ] MERGE
  - [ ] VIEW  #353

- Improve User Experience
  - [ ] IPython terminal* UI #351
  - [ ] Event filtering (slicing) assistant UI #354
  - [ ] Peak processing UI #355
  - [ ] Vanadium peak processing UI #349
  - [ ] Reduced data visualization UI #353

- Instrument operation support
  - [ ] Instrument geometry calibration #350
  - [ ] Vanadium spectrum processing #349

- Software Quality Assurance
  - [ ] System test
  - [ ] Performance test
  - [ ] Deploying PyVDrive on SNS analysis cluster
  - [ ] Documentation for VDRIVE-compatible commands
  - [ ] PyVDrive user manual

**Milestones**

The following milestones will be reached in chronological order.

1. [ ] Enhance *IPython/VDRIVE command* UI (#351). Due date: 2018.12.18

1. [ ] Implement system test framework for VDRIVE-compatible commands.  Due date: 2018.12.21

1. [ ] VBIN system tests and documentation (#347). Due date: 2019.01.04

1. [ ] CHOP system tests and documentation (#348). Due date: 2019.01.11

1. [ ] Performance test with VBIN, CHOP AND *IPython/VDRIVE command* UI. Due date: 2019.01.18

1. [ ] *Release* to instrument team (Yan) to test *IPython/VDRIVE command* UI, VBIN and CHOP.  Due date: 2019.01.21

1. [ ] Re-design the *Reduced data view* UI and *Peak processing*  UI. Due date: 2019.01.25

1. [ ] MERGE system tests and documentation: Due date: 2019.01.29

1. [ ] Improve Vanadium data processing (#349 and #355): Due date: 2019.02.05

1. [ ] *Release* to instrument team (Yan) to test MERGE and Vanadium data processing.  Due date: 2019.02.07

1. [ ] Refactor and test *Event slicing assistant* UI (#354) . Due date: 2019.02.12

1. [ ] Refactor and test *Peak processing* UI (#355).  Due date: 2019.02.19

1. [ ] Refactor and test *Reduced data view* UI (#353). Due date: 2019.02.22

1. [ ] UI robustness test (#352). Due date: 2019.02.28
