### ISSUE TITLE
Slice cyclic data

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#172]
Implement algorithms in PyvDRive/Mantid to create events filter for cyclic (slow) sample log and visualize the result.

**Requirements**
1. load the logs from an HDF5
1. specify number of cycles
1. specify temperature range
1. specify temperature ramping up or down
1. visualize the slicing setup
1. slice the data and save the split logs to
1. use ReducedDataView to visualize the split and reduced data and logs

**Tasks**
The tasks include but are not limited to

- [ ] 1. Search the local minima and local maxima of each cycle.
- [ ] 2. Visualize cyclic sample logs.
- [ ] 3. Create event filters by cycle indexes, rising or falling of sample log value and/or sample log value range.
- [ ] 4. Filter (chop) events.
- [ ] 5. Visualize the cyclic sample log in the output workspaces from **FilterEvents**
- [ ] 6. Generate slicer file (from python script) with 5 columns:
        time_start, time_stop, target_ws, temperature_lowest, temperature_highest
- [ ] 7. Temperature rising: 320 points/4 cycles/80 points per cycle

**Test Case**
IPTS 22862, RUN 172282, Sample: loadframe.furnace2

**Comment by wdzhou** [comment]
Review: /Users/wzz/Projects/PyVDrive/PyVDrive/src/pyvdrive/review
