### ISSUE TITLE
Checklist: Demo-Yan-March-2019

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#191]
**Documentation**
- [ ] 1. IPython/IDL command view
- [ ] 2. VDRIVE commands
   * [ ] VBIN
   * [ ] CHOP
   * [ ] VIEW
   * [ ] VPEAK
   * [ ] MERGE
   * [ ] INFO
- [ ] 3. Chopping assistant GUI
- [ ] 4. Single peak processing GUI
- [ ] 5. Vanadium peak processing GUI

**VDRIVE Commands**
- [ ] VBIN
- [ ] CHOP
- [ ] VIEW
- [ ] VPEAK
- [ ] MERGE
- [ ] INFO
- [ ] Combined VDRIVE commands tests (robustness)

**Reduced Data View GUI**
- [ ] Switch between single run and chopped run
- [ ] Switch between banks
- [ ] Sample log view for chopped run
- [ ] Reset
- [ ] Multiple runs/chopped runs test (robustness)

**Peak Processing UI: Vanadium**

**Peak Processing UI: Single Peak Fitting Assistant**

**Run-chopping Assistant GUI**
