### ISSUE TITLE
Refine cyclic data slicing and visualization

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyVDrive#201]
This is a continuation of #172, #190 and #196.

**Tasks**
- [x] Generate 4 sets of slicers for temperature rising
- [x] Visualize these slicers and export to PNG
- [ ] Slice the data with each of these 4 sets of slicers
  - [ ] Record number of neutrons
  - [ ] Record time span of each chopped data
- [ ] Visualize the sliced data
  - [x] Diffraction data
  - [ ] Sample logs (furnace1)
- [x] Generate N sets of slicers for temperature cooling
- [ ] Visualize these slicers and export to PNG
- [ ] Slice the data with each of these 4 sets of slicers
  - [ ] Record number of neutrons
  - [ ] Record time span of each chopped data
- [ ] Visualize the sliced data
  - [x] Diffraction data
  - [ ] Sample logs (furnace1)
